### ISSUE TITLE
Call/Open a flutter screen through a notification

### ISSUE THREAD

**Issue by Aditi-Mohan** [nowmozillaclub/eldersconnect-senior#20]
To set an alarm I'm using native code, so java for android, to be able to access background services and have pending intents, as this seamed like the most feasible way cause most plugins either don't work or just send local notifications.
I am able to schedule alarms using Java but the notification currently links to an android activity (Ring activity). I want to be able to be able to open a flutter screen by tapping on the widget to give the user an option to dismiss or snooze.

Article I have been referring: https://learntodroid.com/how-to-create-a-simple-alarm-clock-app-in-android/
GitHub repo for it: https://github.com/learntodroid/SimpleAlarmClock

My current approach is to call a dart method from Ring activity using method channel and create a flutter screen in the method.

**Comment by Aditi-Mohan** [comment]
### Update:

It does open a flutter screen but it is opening the sign-in page, as in the first screen.
How do I open a particular page of the app?

**Comment by urmilshroff** [comment]
> ### Update:
> It does open a flutter screen but it is opening the sign-in page, as in the first screen.
> How do I open a particular page of the app?

You will probably need to look into routes or deep links. Or, a more straightforward way would be to have some sort of checker in the `main()` function which will launch a specific page based on how the app was opened (you can use SharedPreferences here).

**Comment by urmilshroff** [comment]
Also, have you tried [android_alarm_manager](https://pub.dev/packages/android_alarm_manager)? It seems to be quite popular and could get the job done easily instead of messing around with native code.

**Comment by khatrivarun** [comment]
At some point I did mention that package. But I couldn't find anything for iOS though

**Comment by Aditi-Mohan** [comment]
> Also, have you tried [android_alarm_manager](https://pub.dev/packages/android_alarm_manager)? It seems to be quite popular and could get the job done easily instead of messing around with native code.

Yes, I did try that initially but it didn't quite work. And that package basically adds all the native code for you (if you take a look at the manifest additions required for the package). Plus, the [article](https://learntodroid.com/how-to-create-a-simple-alarm-clock-app-in-android/) outlines it really well so it was easy to implement in native code.
And as @khatrivarun said it doesn't work for iOS.

Writing our own native code can help add more functionality and implement it for iOS as well.

**Comment by Aditi-Mohan** [comment]
> > ### Update:
> > It does open a flutter screen but it is opening the sign-in page, as in the first screen.
> > How do I open a particular page of the app?
> 
> You will probably need to look into routes or deep links. Or, a more straightforward way would be to have some sort of checker in the `main()` function which will launch a specific page based on how the app was opened (you can use SharedPreferences here).

Yes, I think I'll have to add some sort of check in the main function itself.

**Comment by urmilshroff** [comment]
> > Also, have you tried [android_alarm_manager](https://pub.dev/packages/android_alarm_manager)? It seems to be quite popular and could get the job done easily instead of messing around with native code.
> 
> Yes, I did try that initially but it didn't quite work. And that package basically adds all the native code for you (if you take a look at the manifest additions required for the package). Plus, the [article](https://learntodroid.com/how-to-create-a-simple-alarm-clock-app-in-android/) outlines it really well so it was easy to implement in native code.
> And as @khatrivarun said it doesn't work for iOS.
> 
> Writing our own native code can help add more functionality and implement it for iOS as well.

Okay that's cool, if you're familiar with native code then go ahead.

While adding full iOS support would definitely be great, I don't think it needs to be a priority unless you want it to be. You'll also need a Mac and iPhone to test it properly.
